# Creating a TicTacToe Class

In [19]:
import numpy as np
np.__version__

'2.0.2'

In [34]:
class TicTacToe:
    def __init__(self):
        self.row_count = 3
        self.column_count = 3
        self.action_size = self.row_count * self.column_count
        # self.action_correspondence = np.arange(0, action_size).reshape(self.row_count, self.column_count)

    def get_init(self) -> np.ndarray:
        return np.zeros((self.row_count, self.column_count))

    def get_next_state(self, state: np.ndarray, action: int, player: int) -> np.ndarray:
        row = action // self.column_count
        column = action % self.column_count
        state[row, column] = player
        return state
        # return np.where(state == 0, player, state)

    # def determine_legal(self, state: np.ndarray, action: int) -> bool:
    #     row = action // self.column_count
    #     column = action % self.column_count
    #     if state[row, column] != 0:
    #         return False
    #     return True

    def get_valid_moves(self, state: np.ndarray):
        return (state.reshape(-1) == 0).astype(np.uint8)

    def determine_won(self, state: np.ndarray, action: int) -> bool:
        row = action // self.column_count
        column = action % self.column_count
        player = state[row, column]

        return (
             np.sum(state[row, :] == player * self.column_count)
             or np.sum(state[:, column]) == player * self.row_count
             or np.sum(np.diag(state)) == player * self.row_count
             or np.sum(np.diag(np.fliplr(state))) == player * self.row_count
        )

    def get_value_and_terminated(self, state, action):
        if self.determine_won(state, action):
            return 1, True
        elif np.sum(self.get_valid_moves(state)) == 0:
            return 0, True
        else:
            return 0, False

    def get_opponent(self, player):
        return -player

# Testing TicTacToe

In [35]:
# Initializing the board and players
tictactoe = TicTacToe()
player = 1
state = tictactoe.get_init()
opponent = tictactoe.get_opponent

In [36]:
# Starting for 1 turn
action = 4
state = tictactoe.get_next_state(state, action, player)
print(state)
value, terminated = tictactoe.get_value_and_terminated(state, action)
print(f"The game has {'terminated' if bool(terminated) else 'not terminated'}.")

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
The game has not terminated.


In [37]:
import random

tictactoe2 = TicTacToe()
player = 1
state = tictactoe.get_init()
opponent = tictactoe.get_opponent

while True:
    print(state)
    valid_moves = tictactoe2.get_valid_moves(state)
    print("valid moves", [i for i in range(tictactoe2.action_size) if valid_moves[i] == 1])
    action = int(input(f"{player}:"))

    if valid_moves[action] == 0:
        print("Action not valid")
        continue

    state = tictactoe2.get_next_state(state, action, player)

    value, is_terminated = tictactoe2.get_value_and_terminated(state, action)

    if is_terminated:
        print(state)
        if value == 1:
            print(player, "won")
        else:
            print("draw")
        break

    player = tictactoe2.get_opponent(player)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid moves [0, 1, 2, 3, 4, 5, 6, 7, 8]
1:0
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid moves [1, 2, 3, 4, 5, 6, 7, 8]
-1:1
[[ 1. -1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
valid moves [2, 3, 4, 5, 6, 7, 8]
1:4
[[ 1. -1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
valid moves [2, 3, 5, 6, 7, 8]
-1:2
[[ 1. -1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
valid moves [3, 5, 6, 7, 8]
1:3
[[ 1. -1. -1.]
 [ 1.  1.  0.]
 [ 0.  0.  0.]]
valid moves [5, 6, 7, 8]
-1:5
[[ 1. -1. -1.]
 [ 1.  1. -1.]
 [ 0.  0.  0.]]
valid moves [6, 7, 8]
1:6
[[ 1. -1. -1.]
 [ 1.  1. -1.]
 [ 1.  0.  0.]]
1 won


In [40]:
!git clone https://github.com/GodUnicornIzek/SelfPlayAI.git

Cloning into 'SelfPlayAI'...


In [42]:
!cp /content/AlphaZeroImplementation.ipynb /content/SelfPlayAI/

cp: cannot stat '/content/AlphaZeroImplementation.ipynb': No such file or directory


In [43]:
!ls /content/

sample_data  SelfPlayAI


In [45]:
# Save the current notebook into /content with a specific name
from google.colab import drive, files, _import_hooks
import os

# If you want to save the current notebook with a known name:
!cp "/content/AlphaZeroImplementation.ipynb" "/content/AlphaZeroImplementation.ipynb"

cp: cannot stat '/content/AlphaZeroImplementation.ipynb': No such file or directory


In [46]:
!ls /content

sample_data  SelfPlayAI


In [ ]:
from google.colab import files

# This will prompt you to upload a file if you want to bring it from your local machine
uploaded = files.upload()